# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categray',
            new_name='Category',
        ),
    ]
